# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别')),
            ],
            options={
                'verbose_name': '文档类别',
                'permissions': (('edit_category_prop', '修改文档分类属性'),),
                'default_permissions': (),
                'verbose_name_plural': '文档类别',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('score', models.CharField(max_length=100, verbose_name='打分值')),
                ('date', models.DateTimeField(verbose_name='时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'permissions': (('add_comment', '添加评论'), ('read_comment', '查看评论'), ('edit_comment', '编辑评论')),
                'default_permissions': (),
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.CharField(max_length=100, verbose_name='详细描述')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='文件内容')),
                ('content', models.TextField(blank=True, verbose_name='文档内容')),
                ('date', models.DateField(verbose_name='上传时间')),
                ('tag', models.CharField(max_length=2000, verbose_name='标签')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.Category', verbose_name='类别')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文档',
                'permissions': (('read_document', '查看文档'), ('add_document', '添加文档'), ('edit_document', '编辑文档'), ('comment_document', '评论文档')),
                'default_permissions': (),
                'verbose_name_plural': '文档',
            },
        ),
        migrations.CreateModel(
            name='DocumentAssess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_description', models.CharField(max_length=100, verbose_name='审核详细描述')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审核者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.Document', verbose_name='文档')),
            ],
            options={
                'verbose_name': '文档审核',
                'permissions': (('assess_document', '审核文档'),),
                'default_permissions': (),
                'verbose_name_plural': '文档审核',
            },
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '文档审核状态标志',
                'permissions': (('edit_status_prop', '修改审核状态属性'),),
                'default_permissions': (),
                'verbose_name_plural': '文档审核状态标志',
            },
        ),
        migrations.CreateModel(
            name='ReadTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.Document', verbose_name='文档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='阅读者')),
            ],
            options={
                'verbose_name': '阅读记录',
                'permissions': (('read_readTrace', '查看阅读记录'),),
                'default_permissions': (),
                'verbose_name_plural': '阅读记录',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.Category', verbose_name='订阅分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订阅者')),
            ],
            options={
                'verbose_name': '订阅',
                'permissions': (('edit_subscrube', '编辑订阅内容'),),
                'default_permissions': (),
                'verbose_name_plural': '订阅',
            },
        ),
        migrations.AddField(
            model_name='documentassess',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.DocumentStatus', verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.Document', verbose_name='文档'),
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='评论者角色'),
        ),
    ]
