# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribes',
            field=models.ManyToManyField(through='knowledge.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
