# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribes',
        ),
    ]
