# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20170320_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
