# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:37
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_document_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='myfield',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Markdown'),
        ),
    ]
