# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_document_myfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='myfield',
        ),
        migrations.AddField(
            model_name='document',
            name='contains_File',
            field=models.BooleanField(default=False, verbose_name='是否上传文件'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_Markdown',
            field=models.BooleanField(default=False, verbose_name='Markdown'),
        ),
        migrations.AddField(
            model_name='document',
            name='markdown_content',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Markdown'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='文件内容'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tag',
            field=models.CharField(blank=True, max_length=2000, verbose_name='标签'),
        ),
    ]
