# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_auto_20170322_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.DocumentStatus', verbose_name='审核状态'),
        ),
    ]
