# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20170320_2122'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': (('edit_user_role', '修改用户角色'), ('edit_user_', '修改用户信息'), ('edit_subscrube', '编辑订阅内容')), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_category',
            field=models.ManyToManyField(to='knowledge.Category', verbose_name='订阅分类'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_user',
            field=models.ManyToManyField(related_name='_user_subscribe_user_+', to=settings.AUTH_USER_MODEL, verbose_name='订阅用户'),
        ),
    ]
